name: gh-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: yarn
        run: yarn install

      - name: root-docs
        run: mkdir docs

      - name: build-droff
        run: cd packages/droff && ./node_modules/.bin/tsc

      - name: typedoc-droff
        run: cd packages/droff && ./node_modules/.bin/typedoc src/mod.ts && mv docs ../../docs/droff

      - name: typedoc-droff-helpers
        run: cd packages/droff-helpers && ./node_modules/.bin/typedoc src/mod.ts && mv docs ../../docs/droff-helpers

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
