name: gh-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x

      - name: yarn
        run: yarn install

      - name: build
        run: lerna run prepare

      - name: typedoc
        run: yarn docs

      - name: mkdir-docs
        run: mkdir docs

      - name: mv-droff-docs
        run: mv packages/droff/docs docs/droff

      - name: mv-droff-interactions-docs
        run: mv packages/droff-interactions/docs docs/droff-interactions

      - name: mv-droff-commands-docs
        run: mv packages/droff-commands/docs docs/droff-commands

      - name: mv-droff-helpers-docs
        run: mv packages/droff-helpers/docs docs/droff-helpers

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
